### ISSUE TITLE
Ordering doesnt work

### ISSUE THREAD

**Issue by alexeychikk** [sirlantis/gulp-order#23]
I have task:

``` javascript
gulp.task('js:min', function () {
  return gulp.src(['public/js/*.min.js'])
    .pipe(order([
      'public/js/jquery-1.11.1.min.js',
      'public/js/bootstrap.min.js'
    ]))
    .pipe(print())
    .pipe(concat('main.min.js'))
    .pipe(gulp.dest('tmp'));
});
```

Running gulp js:min will print:

```
[16:28:19] Using gulpfile ~/devster/gulpfile.js
[16:28:19] Starting 'js:min'...
[16:28:19] public/js/bootstrap.min.js
[16:28:19] public/js/jquery-1.11.1.min.js
[16:28:19] public/js/jquery.magnific-popup.min.js
[16:28:19] public/js/jquery.stellar.min.js
[16:28:19] public/js/jquery.touchSwipe.min.js
[16:28:19] public/js/owl.carousel.min.js
[16:28:19] public/js/retina-1.1.0.min.js
[16:28:19] public/js/wow.min.js
[16:28:19] Finished 'js:min' after 46 ms
```

**Comment by eagor** [comment]
try adding [base](https://github.com/sirlantis/gulp-order#base) option like this:
```
.pipe(order([
      'public/js/jquery-1.11.1.min.js',
      'public/js/bootstrap.min.js'
    ], { base: './' }))
```

**Comment by Gobd** [comment]
If the base doesn't solve it for you (it didn't help me) try this out.
```
    .pipe(order([
      '**/*/jquery-1.11.1.min.js',
      '**/*/bootstrap.min.js'
    ]))
```

**Comment by NathanQ** [comment]
adding `, { base: './' }` to the end of the order list worked (suhweet! good tip @eagor ), but this confusing. Not complaining, but adding the complete path which included the current directory marker errors with "Error: Don't start patterns with `./` - they will never match. Just leave out `./`" lol

**Comment by fonziemedia** [comment]
adding , { base: './' } worked for me too. Maybe this should be added to the https://www.npmjs.com/package/gulp-order usage instructions.

Thanks!

**Comment by wwwanyu** [comment]
add `{base: './}` is not work for me, and [here is my code](https://github.com/wwwanyu/gulp4-concat-js-in-order/tree/master)
