### ISSUE TITLE
Publish v1.2.0 to npm

### ISSUE THREAD

**Issue by rejas** [sirlantis/gulp-order#31]
would be nice to get it out to other people @sirlantis

**Comment by thrakish** [comment]
I know Gulp is not very exposed to Regexp DOS attacks (It's not outwardly facing), but will this update the minimatch dependency to 3.0.2? Should I open a separate issue, or make a pull request? This module has been really helpful and I would like to help. Thanks.

**Comment by rejas** [comment]
current code uses `"minimatch": "~3.0.4"` so yes, if an npm update is published that would get released too.

**Comment by thrakish** [comment]
Thanks!

**Comment by davejagoda** [comment]
@sirlantis would you please publish a new version? If I am reading the output of `npm owner ls gulp-order` correctly, you are the only one who has the permissions to do so.

**Comment by sijojlouis** [comment]
+1

**Comment by rejas** [comment]
pinging @sirlantis hoping we can get a new release published... i am open to maintaining the repo in case you dont have enough time on your hand...

**Comment by elliot-nelson** [comment]
Any word from owner on this one?  Seems to me like there's a couple things this repo desperately needs - one, basic updates (like minimatch), and two, for some type of customized ordering (I see a couple PRs with different approaches).

**Comment by rejas** [comment]
well @sirlantis seems to be active on twitter, maybe its an option to ping him there?

**Comment by sirlantis** [comment]
I've been under a rock for the last few months. I published 1.2.0 to npm.
